# Generated by Django 5.2 on 2025-04-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('stance', models.CharField(max_length=20)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reach_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('division', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BoxerStats',
            fields=[
                ('boxer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='boxerstats.boxer')),
                ('strength', models.PositiveSmallIntegerField()),
                ('stamina', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('reflex', models.PositiveSmallIntegerField()),
                ('boxing_iq', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FightRecord',
            fields=[
                ('boxer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fight_record', serialize=False, to='boxerstats.boxer')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
