# Generated by Django 5.2 on 2025-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxerstats', '0003_rename_height_cm_boxer_height_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightrecord',
            name='losses_by_knockout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fightrecord',
            name='wins_by_knockout',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
