# Generated by Django 5.2 on 2025-04-28 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxerstats', '0004_fightrecord_losses_by_knockout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxer',
            name='height_metric',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='boxer',
            name='reach_metric',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
