# Generated by Django 5.2 on 2025-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxerstats', '0005_alter_boxer_height_metric_alter_boxer_reach_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxerstats',
            name='heart',
            field=models.PositiveSmallIntegerField(default=97),
        ),
    ]
