# Generated by Django 5.0.6 on 2024-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxingHub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('loves', models.IntegerField()),
            ],
        ),
    ]
